// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgbeskcqdesfsbgxggds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYmVza2NxZGVzZnNiZ3hnZ2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzYyNjksImV4cCI6MjA2MjU1MjI2OX0.lQwWUUxAkFTZABsOonuKcAJMc9SK2k_96DO_I2Pls2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);